export const SEND_MESSAGE = 'SEND_MESSAGE';
export const USER_CONNECTED = 'USER_CONNECTED';
export const USER_DISCONNECTED = 'USER_DISCONNECTED';
export const RECEIVE_MESSAGE = 'RECEIVE_MESSAGE';
export const SET_ONLINE_USERS = 'SET_ONLINE_USERS';