module.exports = {
    RECEIVE_MESSAGE : "RECEIVE_MESSAGE",
    LOGIN_FAILURE: "LOGIN_FAILURE",
    LOGIN_SUCCESS : "LOGIN_SUCCESS",
    USER_DISCONNECTED : "USER_DISCONNECTED",
    USER_CONNECTED: "USER_CONNECTED"
}